// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnegzwhvzqpstueniulp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZWd6d2h2enFwc3R1ZW5pdWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDM3MTgsImV4cCI6MjA2NTY3OTcxOH0.DFqcxb8VZuiyIHqhb7bFD0qDi1ylAX__64Uf7tLcEd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);